id = "extempore"
name = "Extempore"
description = "Extempore language extension for Zed"
version = "0.1.0"
schema_version = 1
authors = ["Siarhei Lunski <loonskai@gmail.com>"]
repository = "https://github.com/loonskai/zed-extempore"
