id = "extempore"
name = "Extempore"
description = "Extempore language extension for Zed"
version = "0.1.0"
schema_version = 1
authors = ["Siarhei Lunski <loonskai@gmail.com>"]
repository = "https://github.com/loonskai/zed-extempore"

[grammars.extempore]
repository = "https://github.com/loonskai/tree-sitter-extempore"
rev = "dba2b6f57e550fbed5b96171e1cd2d50b3421b7b"
